### PR TITLE
[DO NOT MERGE] Update to Lanterna 3.0

### PR DESCRIPTION
**Pull request by AdamNiederer**
This pull request should allow clojure-lanterna to use lanterna@3.0.0 without any API breakage. Just to be safe, I bumped the major version because of how sweeping the changes are.

- New function: `get-keystroke[-blocking]` returns a dict of `{:key [char] :shift [bool] :ctrl [bool] :alt [bool]}`. `get-key[-blocking]` has been redefined in terms of this function for simplicity's sake
- Support for new obscure SGR codes, just in case somebody wanted to use them
- `get-key` and friends are now in their own module, which works on both Screens and Terminals
- Lots of parameters were cleaned up

Stuff that still needs to be done:
- [x] Fix a bug causing terminals to only render changes when being resized (Any ideas?)
- [x] Fix font initialization bug

### CODE REVIEW

**Comment by Ragnaroek** [comment]
I think this project is dead. I tried something like this a year ago:
https://github.com/sjl/clojure-lanterna/pull/19

Maybe we should join forces and fork this project with lanterna 3?

**Comment by AdamNiederer** [comment]
Looks like you're right. Lanterna 3 is still technically a beta release right now, but I think a fork might be a good idea.

**Comment by Martin-S-Weber** [comment]
I'm still awaiting official blessing in the form of a github-visible statement, yet...
Hi there! I'm the new maintainer of clojure-lanterna and the zombie has risen from the dead.
Looking at the pull-up to lanterna 3.0-beta right now.

**Comment by Martin-S-Weber** [comment]
I adapted this pull request into the lanterna-3 branch of my fork with some adaptions, adding .flush where necessary and breaking the old API a bit less.

**Comment by AdamNiederer** [comment]
Hello,
I did some extra work adding features to my branch, although I broke the API in several more places for the fork. Some of the architectural changes might be of interest. I'll push it up to this branch later today.

**Comment by Martin-S-Weber** [comment]
Although this project is still pre-1.0.0, I was tasked by @sjl to minimize API breakage. I'll look into your further work, thanks @AdamNiederer ! Even though I realized I used the wrong github entity on the site, heh. repo's moving again :unamused:

**Comment by MultiMUD** [comment]
And it moved. Track progress under "my" fork.

**Comment by AdamNiederer** [comment]
I've just added the new commits. These break the API with impunity, but there's some good stuff in there.

**Comment by MultiMUD** [comment]
Couple of notes to this:
* I suggest renaming the project (ATM it's impossible to determine the original clojure-lanterna from your [fw]ork)
* I suggest fixing the doc strings of some of your changed fns, e.g. your terminal/get-terminal's docstring and code are quite out of sync
* I wouldn't call this a "1.0.0" yet (neither my fork, nor yours). semver is picky: going 1.0.0 fixes your public API and further changes MUST (that's an RFC MUST) increase appropriate MAJOR, MINOR or PATCH
* I am trying to keep the API more stable, as per request of @sjl 
* don't let any of the above hold you back, as  I will continue to happily adapting your work, long live open source :D

**Comment by MultiMUD** [comment]
Also, if you have future feature requests, suggestions, issues or pull requests, please direct them to "my" repo; your pull request won't find its way into @sjl 's clojure-lanterna (parts of the diff made it into "mine" though, currently on lanterna3 branch)

**Comment by MultiMUD** [comment]
Code has been pulled, lanterna-3 migration is on lanterna3 branch. Closing this request.

**Pull request closed without merging**
